sudo: required
language: node_js

before_script:
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-0}'/g' ./magic-package-remote-help/DEBIAN/control
- sed -i 's/$URL_REGISTER_SERVER/'${URL_REGISTER_SERVER}'/g' ./magic-package-remote-help/DEBIAN/preinst
script:
- dpkg-deb --build magic-package-remote-help
deploy:
  provider: releases
  api_key:
    secure: V8OM+eEZmSBR9Gs9AuBxLZcffPiNyXVEli6rJGBvzIorjG/l27I7cTpP8fq3BeX423KT8Ag3A8QQ7nwaEr/TZiVRGqxWTlu9matK39kdrvq/B9kjvhgFPWOIO20SZWVuvro4hUiKmHMtglCv3JQECIST5+yzrLdk3eJg7lnsL9FpL5uGm2gMhZ/CR5Mkl81eGa84wQe7yJAX0BP6Zd67HfbxRDyy1r3ICH8dxB+zAMi2/EymlpGqPaKQHIPG+ElGkdn5OjFrmtx72JYM3hyPNdSv00T+nUawoz3H505+NZ2bzavAKkNvrejpr2QY4dtG8Wdif97QBAXfA5d4z6FGQClE91iejJpaSU/I7P6vY1nzQh1Kv//T6OCrws5WsgcwJ1MXDUUkQjI9QG0BvTh6d3SOBCv7KRjnGRbk170Q0GX4PSehMts7QuyoFYyi2Yffi6VdFS3GMXv80urCAFiPeIVrzg0FbVtr7+AaJRLUKTlwMK1aHp5mUgh7vNAEwUi7UMfL862m+Pa+75i7OohuL4vQzVBVy8K4i9S23j1JRbMfrVbER1I33dE57pVxAS3thQsNS6kr5OVPfVL7mFSmLzhd0BUmKehYD22ytSYRjiHDAfJo8lebijzyj1JVhuMChMAZn4R12jfKl5gzLc3bRnMR0nqwvkHOZCpgUmA51Qo=
  file: magic-package-remote-help.deb
  on:
    tags: true
