sudo: required
language: node_js
before_script:
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-${TRAVIS_JOB_NUMBER:-0}}'/g' ./magic-package-remote-help/DEBIAN/control
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-${TRAVIS_JOB_NUMBER:-0}}'/g' ./magic-package-remote-help/usr/local/bin/magic-package-remote-help
- sed -i 's/$USER_ADMIN/'${USER_ADMIN}'/g' ./magic-package-remote-help/DEBIAN/postinst
- sed -i 's/$PASSWORD_ADMIN/'${PASSWORD_ADMIN}'/g' ./magic-package-remote-help/DEBIAN/postinst
- sed -i 's/$USER_ADMIN/'${USER_ADMIN}'/g' ./magic-package-remote-help/DEBIAN/postrm
- sed -i 's/$PASSWORD_ADMIN_64/'`echo "${PASSWORD_ADMIN}"|base64`'/g' ./magic-package-remote-help/usr/local/bin/magic-package-remote-help-configure
- sed -i 's/$URL_REGISTER_SERVER/'$([ "$TRAVIS_TAG" ] && echo "$URL_REGISTER_SERVER" || echo "$URL_REGISTER_SERVER_BETA")'/g' ./magic-package-remote-help/DEBIAN/preinst
- sed -i 's/$URL_REGISTER_SERVER/'$([ "$TRAVIS_TAG" ] && echo "$URL_REGISTER_SERVER" || echo "$URL_REGISTER_SERVER_BETA")'/g' ./magic-package-remote-help/usr/local/bin/magic-package-remote-help-list-user
script:
- dpkg-deb --build magic-package-remote-help

deploy:
- provider: packagecloud
  repository: "magic-package-beta"
  username: "krack"
  token:
    secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
  dist: "ubuntu/disco"
  skip_cleanup: true
  on:
    tags: false
- provider: packagecloud
  repository: "magic-package-beta"
  username: "krack"
  token:
     secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
  dist: "ubuntu/bionic" 
  skip_cleanup: true
  on:
     tags: false 
- provider: packagecloud
  repository: "magic-package-beta"
  username: "krack"
  token:
     secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
  dist: "ubuntu/cosmic" 
  skip_cleanup: true
  on:
     tags: false 
- provider: packagecloud
  repository: "magic-package"
  username: "krack"
  token:
    secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
  dist: "ubuntu/disco"
  skip_cleanup: true
  on:
    tags: true
- provider: packagecloud
  repository: "magic-package"
  username: "krack"
  token:
     secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
  dist: "ubuntu/bionic" 
  skip_cleanup: true
  on:
     tags: true 
- provider: packagecloud
  repository: "magic-package"
  username: "krack"
  token:
     secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
  dist: "ubuntu/cosmic" 
  skip_cleanup: true
  on:
     tags: true 