#!/bin/bash
#get openvpn configuration since server 
vpnConf=/etc/openvpn/client.conf    
if [ -f $vpnConf ]; then
   echo "Configuration vpn already exist."
else
	echo "Configuration of vpn..."
	mkdir -p etc/openvpn/
	curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{\"name\":\"`hostname`\"}" "http://$URL_REGISTER_SERVER/api/clients/" -o$vpnConf
	echo "Configuration of vpn done"
fi

echo "install"
